Copy for comment
andrsvsrg/reactToDo pull request #1
Opened 2022-07-24 20:42 UTC by andrsvsrg

Up

2022-07-26 12:14 UTC, stanislav-grin requested changes

2022-07-26 12:14 UTC, stanislaw-grin commented on src/App.css
> +.app {
Оставляй всегда один отступ между блоками:

```css
.app {
   ...
}

.another-class {
   ...
}
```

2022-07-26 12:14 UTC, stanislaw-grin commented on src/App.js
> +import moment from 'moment'
на будущее - лучше не использовать эту библиотеку, она deprecated и плохо продуманна, из-за чего ради какого-то одного метода ты тянешь 100500 файлов в свой проект, раздувая его

2022-07-26 12:14 UTC, stanislaw-grin commented on src/App.js
> +import moment from 'moment'
Взамен её рекомендую date-fns

2022-07-26 12:14 UTC, stanislaw-grin commented on src/App.js
> +import './App.css'
стили лучше всего импортировать в первую очередь (в самом верху)

2022-07-26 12:14 UTC, stanislaw-grin commented on src/App.js
> +
лишний отступ

2022-07-26 12:14 UTC, stanislaw-grin commented on src/App.js
> +    JSON.parse(localStorage.getItem('items')) || {}
`JSON.parse(localStorage.getItem('items'))` будет вызываться на каждый ре-рендер. А работа с local storage - тяжелая и медленная для браузера. Если нужно что-то посчитать для initial state, заверни это в функцию:
```js
const [toso, setToDo] = useState(() => JSON.parse(localStorage.getItem('items')) || {})
```

2022-07-26 12:14 UTC, stanislaw-grin commented on src/App.js
> +  const [todo,setToDo] = useState(
`todo,setToDo` слиплись - после запятых всегда пробелы.
Установи себе [Prettier](https://prettier.io/docs/en/index.html)
[Install](https://prettier.io/docs/en/install.html)
Но важно сначала научиться самому соблюдать кодстайл, сторонние тулзы должны лишь немного помогать там, где завтыкал

2022-07-26 12:14 UTC, stanislaw-grin commented on src/App.js
> +
Не делай кучу лишних оступов. Максимум - 1 отступ, между блоками или между логически разными частями кода

2022-07-26 12:14 UTC, stanislaw-grin commented on src/App.js
> +  const [selectedDay, setSelectedDay] = useState(moment())
moment() на каждый ре-рендер

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +    if (value.trim()) {
отступ перед `if`

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +        <input className="addtodo_input"
все классы именуем через дефис - `add-todo-input`

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +               onKeyPress={ (e) => keyPressAddItem(e) }
можно так `onKeyPress={ keyPressAddItem }`

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +      <p className='addtodo_selected-date'> {selectedDay.format('DD.MM.YYYY')}</p>
для аттрибутов используем двойные кавычки ""

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +      <p className='addtodo_selected-date'> {selectedDay.format('DD.MM.YYYY')}</p>
format будет вызываться каждый раз, даже если selectedDay не менялся

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +        <button className="addtodo_button" onClick={ saveToDo }>Add a task</button>
так Save ToDo или Add Task?

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +        <input className="addtodo_input"
все инпуты и кнопки - кандидаты на общие компоненты

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +  function defaultPos() {
названия функций должны говорить о том, что они делают или что возвращают. На спичках экономить тоже не надо (Pos)

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +  function defaultPos() {
`getDefaultTaskPosition` например

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +    if (code === 13) {
13 - magic number. В константу

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +    const code = e.keyCode || e.which
в реакте все dom события заворачиваются в синтетический event специльно для того чтобы не париться о кросс-браузерности

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +  function keyPressAddItem(e) {
события начинаются с `on` -> `onKeyPress`

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +    return { x: defaultWidth, y: defaultHeight };
перед return всегда отступ

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +    const defaultWidth = Math.floor(Math.random() * (width < 300 ? width : width - 300)) + 1
что за магические числа?

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +    if (value.trim()) {
если есть какое-то условие, и нет блока else, то лучше сразу выйти из функции, если условие не прошло, таким образом сократить вложенность кода:

```js
if (!value.trim()) {
  return
}

... other code
```

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +          status: true,
`status` обычно подразумевает какую-то строку, в данном случае непонятно что означает true. Если это done/не done, тогда поле можно назвать completed например

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +      }
Два блока кода фактически идентичны. Можно упростить:

```js
const todoCopy = JSON.parse(JSON.stringify(todo))

todoCopy[selectDayStr] = todoCopy[selectDayStr] || []

todoCopy[selectDayStr].push({ ... })
```

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +          title: value,
тут уже не нужен trim?

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/AddToDo/AddToDo.js
> +  function defaultPos() {
Также нужно вынести за пределы компонента, функция не работает в контексте его состояния. Так она не будет пересоздаваться каждый раз + компонент станет проще читать и понятнее

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/Calendar/Calendar.js
> +  moment.updateLocale('en', { week: { dow: 1 } });
на каждый ре-рендер будет

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/Calendar/Calendar.js
> +  const [currentWindowCalendar, setCurrentWindowCalendar] = useState(setValuesCurrWindow(moment().year(),moment().month()))
то же самое

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/Calendar/Calendar.js
> +    let currDay = startDay.subtract(1, 'day').clone();
почему let?

2022-07-26 12:14 UTC, stanislaw-grin commented on src/components/Calendar/Calendar.js
> +  }
вынести за пределы компонента и переименовать на что-то более понятное

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/Calendar/Calendar.js
> +  function changeMonthSelect(e) {
onMonthChange

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/Calendar/Calendar.js
> +  function changeYearSelect(e) {
onYearChange

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/Calendar/Calendar.js
> +  function todayClickButton() {
onTodayClick

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/Calendar/Calendar.js
> +  function nextMonthBtn() {
onNextMonthClick

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/Calendar/Calendar.js
> +        <select value={selectMonthValue} onChange={(e) => changeMonthSelect(e)} className="calendar_select calendar_select_month">  {/* SELECT MONTH */ }
То, что тебе приходится оставлять комментарии в jsx - признак того, что компонент написан даже для тебя непонятно и сложно, хотя ты его автор. Компонент нужно максимально разбивать на мелкие компоненты

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/Calendar/Calendar.js
> +            defaultValues.years.map((year, index) => {
индексы для key использовать нежелательно

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/Calendar/Calendar.js
> +              const dataClasses =  addClassDate(dateItem)
внезапно в jxs снова какой-то JS и логика) Такого не должно быть. JSX должен оставаться чистым, ты должен видеть просто структуру компонента (html), а сейчас это невозможно сделать.
Выходов два:
1. Не пихать функции в JSX, а вынести их за пределы
2. Для конструирования классов можно использовать библиотеку `classnames`

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +            {
избегай условий в JSX, если что-то рендерится по условию - нужно хотя бы вынести это в отдельный компонент и либо он будет решать, нужно ли ему рендериться, либо здесь просто останется

```js
{ edit === item.id ? <OneComonent/> : <AnotherComponent/> }
```

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +  const [edit, setEdit] = useState(null)
edit - это глагол, если здесь подразумается состояние - тогда лучше isEditing

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +  selectedDay = selectedDay.format('DDMMYYYY')
каждый ре-рендер...

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +    todoCopy[selectedDay] = [...todo[selectedDay]].filter((obj) => obj.id !== id)
для чего разворачивается  [...todo[selectedDay]]? filter не мутирует массив

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +    todoCopy[selectedDay] = [...todo[selectedDay]].filter((obj) => {
для чего используется filter? Ты не фильтруешь список, а пробегаешься по нему и мутируешь один объект

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +    todoCopy[selectedDay] = [...todo[selectedDay]].map((item) => {
для чего разворачивание?

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +      { todo[selectedDay] ?
сделай ранний return если тасок нет, будет минус 1 уровень вложенности и сложности

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +          offsetParent={document.querySelector('.draggable_fild')}
используй refs и useRef для этого

2022-07-26 12:14 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +    setEdit(id)
ага - edit - это id. Тогда лучше editingId

2022-07-26 16:26 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +const ListItem = ({ todo, setToDo , setSelectedDay, selectedDay}) => {
Это не ListItem, а List. Тут список тудушек. Внизу в JSX у тебя есть отдельно див с классом list-item, и вот это уже - отдельно взятый айтем, и он должен уйти в отдельный компонент. Туда же вместе с ним должны уйти и все функции, которые работают с тудушкой, а передавать туда надо уже конкретный todoItem. Таким образом каждый ListItem будет точно знать с каким объектом он работает и не придётся постоянно искать в списке нужный. 

Начни с того чтобы вынести отдельным компонентом ToDoItem (то, что у тебя называется list-item в jsx).
Этот компонент переименовать в TodoList

2022-07-26 16:27 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +const ListItem = ({ todo, setToDo , setSelectedDay, selectedDay}) => {
Потом это позволит нам избавиться от постоянного клонирования todo и поиска нужной тудушки

2022-07-26 16:28 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +                    <img src={ iconCross } alt="close" width={ '15px' } height={ '15px' }/>
строковые аттрибуты через "", не через {}

2022-07-26 16:28 UTC, stanislav-grin commented on src/components/ListItem/ListItem.js
> +                  <button className="listitem_btn" onClick={ () => statusToDo(item.id) }>
кнопку в отдельный компонент

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/Header/Header.js
> +      <h1  style={{textAlign: 'center', fontSize: '24px', marginTop:'0' , paddingTop: '20px'}}>To Do List</h1>
Стили нужно указывать через css. 
.header h1 {
  font-size: 24px;
  ....
}
Или добавить класс к h1
<h1  className="header-title"
Когда ты указываешь через style что-то это будет тяжело перекрыть в css из-за весов селекторов

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/Header/Header.js
> +      <h1  style={{textAlign: 'center', fontSize: '24px', marginTop:'0' , paddingTop: '20px'}}>To Do List</h1>
style тяжело и неправильно преекрывать потом в css

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/AddToDo/AddToDo.js
> +
Я б здесь оформил константы, которые ты юзаешь в компоненте основаные  на props, такие как

```
const selectedDayTitle = selectedDay.format('DD.MM.YYYY')
const selectedDayTasksId =  selectedDay.format('DDMMYYYY')
const selectedDayTasks = todo[selectedDayTasksId]
```

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/AddToDo/AddToDo.js
> +
А потом, прочитав про useMemo (оч крута вещь) сделал так
```
selectedDayTasks = useMemo(() => {
  const selectedDayTasksId = selectedDay.format('DDMMYYYY')

  return todo[selectedDayTasksId]
}, [selectedDay, todo])
```

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/AddToDo/AddToDo.js
> +
И так ж для title

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/AddToDo/AddToDo.js
> +const AddToDo = ({ todo, setToDo, selectedDay }) => {
Этот компонент работает по сути с определенным днём, а приходят методы для работы со всем.
Должно приходить что-то вроде вместо всего todo -> selectedDayTasks, вместо setToDo -> setSelectedDayTasks

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/AddToDo/AddToDo.js
> +
И с учётом того что в этот компонент будет приходит selectedDayTasks это перейдет в App,js.
И в App.js бдето что-то такое
```
 <AddToDo selectedDay={selectedDay}
               tasks={selectedDayTasks} // или value
               onChange={setSelectedDayTasks}/> 
```

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/AddToDo/AddToDo.js
> +  function saveToDo() {
функцию нудно упростить и разбить
ЧТо-то вроде такого
```

  function createNewTask(value) {
    return {
      id        : uuid(),
      title     : value,
      status    : true,
      defaultPos: defaultPos(),
      color     : randomColor({ luminosity: 'light' })
    }
  }

  function saveToDo() {
    const value = value.trim()

    if (value) {
      const newTask = createNewTask(value)

      // или вместо setSelectedDayTasks передавать в компонент сразу addTask addTask(newTask)
      setSelectedDayTasks([...selectedDayTasks, newTask]) 
    }
  }
```

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/AddToDo/AddToDo.js
> +  function saveToDo() {
createNewTask так ж за пределы компонента, так как его работа не зависит от состояния или пропсов компонента, только от аргумента по сути

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/AddToDo/AddToDo.js
> +      <div className="addtodo_div">
Плохое название для класса, когда в нём юзаются всякие div или h1 (но юзать checkbox, input или btn нормальн), это можно было б реализовать так
```
<div className="addtodo">
...
```
CSS
addtodo div {
 ...
}

Но это тоже не очень, лучше длять конкретный класс этому div и работать с ним, например add-task-container-controls

2022-07-26 18:01 UTC, viktor-liablin commented on src/components/AddToDo/AddToDo.js
> +    <div>
сюда я  добавил класс add-task-container и в стилях для б ему
```
    display: flex;
    flex-direction: column;
    align-items: center;
```
Тогда б еще ушло 
.addtodo_selected-date центрирование текста, и даже можно было б удалить .addtodo_div

2022-07-28 12:09 UTC, merged

2022-08-10 11:57 UTC, andrsvsrg commented on src/App.css
> +.app {
+
у себя поправил, запушу с остальными изменениями

2022-08-10 11:59 UTC, andrsvsrg commented on src/App.js
> +
+

2022-08-10 12:01 UTC, andrsvsrg commented on src/App.js
> +    JSON.parse(localStorage.getItem('items')) || {}
fix

2022-08-10 12:04 UTC, andrsvsrg commented on src/App.js
> +  const [todo,setToDo] = useState(
fix

2022-08-10 12:04 UTC, andrsvsrg commented on src/App.js
> +
fix

2022-08-10 12:07 UTC, andrsvsrg commented on src/App.js
> +  const [selectedDay, setSelectedDay] = useState(moment())
fix

2022-08-10 13:51 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +    if (value.trim()) {
fix

2022-08-10 14:20 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +        <input className="addtodo_input"
fix

2022-08-10 14:22 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +               onKeyPress={ (e) => keyPressAddItem(e) }
fix

2022-08-10 14:48 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +      <p className='addtodo_selected-date'> {selectedDay.format('DD.MM.YYYY')}</p>
fix

2022-08-10 14:50 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +      <p className='addtodo_selected-date'> {selectedDay.format('DD.MM.YYYY')}</p>
fix

2022-08-10 15:02 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +        <button className="addtodo_button" onClick={ saveToDo }>Add a task</button>
fix

2022-08-14 10:55 UTC, andrsvsrg commented on src/App.js
> +import './App.css'
fix

2022-08-14 14:08 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +        <input className="addtodo_input"
fix

2022-08-14 16:08 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +    if (code === 13) {
fix

2022-08-14 16:08 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +    const code = e.keyCode || e.which
fix

2022-08-14 16:08 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +  function keyPressAddItem(e) {
fix

2022-08-15 08:23 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +  function defaultPos() {
fix

2022-08-15 08:23 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +    const defaultWidth = Math.floor(Math.random() * (width < 300 ? width : width - 300)) + 1
fix

2022-08-15 08:24 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +          status: true,
fix

2022-08-15 08:27 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +      }
fix

2022-08-15 08:27 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +          title: value,
fix

2022-08-15 08:28 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +  moment.updateLocale('en', { week: { dow: 1 } });
fix

2022-08-15 08:28 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +  const [currentWindowCalendar, setCurrentWindowCalendar] = useState(setValuesCurrWindow(moment().year(),moment().month()))
fix

2022-08-15 08:28 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +    let currDay = startDay.subtract(1, 'day').clone();
fix

2022-08-15 08:29 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +  }
fix

2022-08-15 08:32 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +  function changeMonthSelect(e) {
fix

2022-08-15 08:32 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +  function changeYearSelect(e) {
fix

2022-08-15 08:33 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +  function todayClickButton() {
fix

2022-08-15 08:33 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +  function nextMonthBtn() {
fix

2022-08-15 08:35 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +            defaultValues.years.map((year, index) => {
fix

2022-08-15 08:36 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +              const dataClasses =  addClassDate(dateItem)
fix временно вынес за JSX, буду разбираться с лучшим решением

2022-08-15 08:38 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +  selectedDay = selectedDay.format('DDMMYYYY')
fix

2022-08-15 08:39 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +    todoCopy[selectedDay] = [...todo[selectedDay]].filter((obj) => obj.id !== id)
fix

2022-08-15 14:27 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +    todoCopy[selectedDay] = [...todo[selectedDay]].filter((obj) => {
fix

2022-08-15 14:28 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +    todoCopy[selectedDay] = [...todo[selectedDay]].map((item) => {
fix

2022-08-15 15:09 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +          offsetParent={document.querySelector('.draggable_fild')}
fix

2022-08-15 15:09 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +    setEdit(id)
fix

2022-08-16 12:45 UTC, andrsvsrg commented on src/components/Calendar/Calendar.js
> +        <select value={selectMonthValue} onChange={(e) => changeMonthSelect(e)} className="calendar_select calendar_select_month">  {/* SELECT MONTH */ }
fix

2022-08-16 12:46 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +            {
fix

2022-08-16 12:47 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +  const [edit, setEdit] = useState(null)
fix

2022-08-16 13:09 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +                  <button className="listitem_btn" onClick={ () => statusToDo(item.id) }>
fix

2022-08-16 13:17 UTC, andrsvsrg commented on src/components/Header/Header.js
> +      <h1  style={{textAlign: 'center', fontSize: '24px', marginTop:'0' , paddingTop: '20px'}}>To Do List</h1>
fix

2022-08-17 20:37 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +  function saveToDo() {
fix

2022-08-17 20:40 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +const AddToDo = ({ todo, setToDo, selectedDay }) => {
fix

2022-08-17 20:40 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +
fix

2022-08-17 20:41 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +    <div>
fix

2022-08-17 20:41 UTC, andrsvsrg commented on src/components/AddToDo/AddToDo.js
> +      <div className="addtodo_div">
fix

2022-08-17 20:45 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +                    <img src={ iconCross } alt="close" width={ '15px' } height={ '15px' }/>
fix

2022-08-17 20:47 UTC, andrsvsrg commented on src/components/ListItem/ListItem.js
> +const ListItem = ({ todo, setToDo , setSelectedDay, selectedDay}) => {
fix